/* eslint-disable global-require */

module.exports = {
  settings: {
    bullet: '-',
    fences: true,
    listItemIndent: '1',
    incrementListMarker: false,
    paddedTable: false,
  },
  plugins: [
    require('remark-preset-lint-recommended'),
    require('remark-comment-config'),
    require('remark-validate-links'),
    [require('remark-lint-blockquote-indentation'), 2],
    [
      require('remark-lint-checkbox-character-style'),
      { checked: 'x', unchecked: ' ' },
    ],
    require('remark-lint-checkbox-content-indent'),
    [require('remark-lint-code-block-style'), 'fenced'],
    require('remark-lint-definition-case'),
    require('remark-lint-definition-spacing'),
    [require('remark-lint-emphasis-marker'), '_'],
    require('remark-lint-fenced-code-flag'),
    [require('remark-lint-fenced-code-marker'), '`'],
    [require('remark-lint-file-extension'), 'md'],
    require('remark-lint-final-definition'),
    require('remark-lint-first-heading-level'),
    require('remark-lint-heading-increment'),
    [require('remark-lint-heading-style'), 'atx'],
    [require('remark-lint-link-title-style'), '"'],
    require('remark-lint-list-item-content-indent'),
    [require('remark-lint-list-item-indent'), 'space'],
    [require('remark-lint-maximum-heading-length'), 100],
    [require('remark-lint-maximum-line-length'), 120],
    require('remark-lint-no-consecutive-blank-lines'),
    ['remark-lint-no-emphasis-as-heading', false], // disabled
    require('remark-lint-no-file-name-articles'),
    require('remark-lint-no-file-name-consecutive-dashes'),
    require('remark-lint-no-file-name-irregular-characters'),
    require('remark-lint-no-file-name-mixed-case'),
    require('remark-lint-no-file-name-outer-dashes'),
    require('remark-lint-no-heading-indent'),
    ['remark-lint-no-heading-punctuation', false], // disabled
    require('remark-lint-no-html'),
    [
      require('remark-lint-no-missing-blank-lines'),
      { 'except-tight-lists': true },
    ],
    require('remark-lint-no-multiple-toplevel-headings'),
    require('remark-lint-no-shell-dollars'),
    require('remark-lint-no-table-indentation'),
    require('remark-lint-no-tabs'),
    [require('remark-lint-ordered-list-marker-value'), 'one'],
    [require('remark-lint-rule-style'), '---'],
    [require('remark-lint-strong-marker'), '*'],
    [require('remark-lint-table-cell-padding'), 'padded'],
    ['remark-lint-table-pipe-alignment', false], // disabled
    require('remark-lint-table-pipes'),
    [require('remark-lint-unordered-list-marker-style'), '-'],
  ],
};
